{"uuid": "a2061e4e-129e-4d57-bbf1-e75fd94ad5fb", "children": ["28a90104-d70d-495b-b609-956b8cd6ba34"], "befores": [{"name": "env_setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'C:\\Users\\chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home\n\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py\", line 949, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py\", line 775, in call_fixture_func\n    res = next(it)\n  File \"/Users/richeliolabrague/PycharmProjects/Dropdown/GIthubTest/testinterview/amazon/test_search.py\", line 13, in env_setup\n    driver = webdriver.Chrome(\"C:\\\\Users\\\\chromedriver.exe\")\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py\", line 73, in __init__\n    self.service.start()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/common/service.py\", line 83, in start\n    os.path.basename(self.path), self.start_error_message)\n"}, "start": 1574213086409, "stop": 1574213086423}], "start": 1574213086409, "stop": 1574213086552}